services:
  - type: web
    name: aeio-mr
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server_gemini:app
    envVars:
      - key: GEMINI_API_KEY
        value: your_actual_gemini_key_here
      - key: PORT
        value: 8000